index:
    path: /user/
    controller: App\Controller\UserController::index
    methods: GET

user_list:
    path: /user/list/
    controller: App\Controller\UserController::list

register_user:
    path: /user/register
    controller: App\Controller\UserController::registerUser
    methods: POST

view_user:
    path: /user/{id}
    controller: App\Controller\UserController::viewUser
    methods: GET

delete_user:
    path: /user/delete/{id}
    controller: App\Controller\UserController::deleteUser
    methods: POST

update_user:
    path: /user/edit/{id}
    controller: App\Controller\UserController::edit
    methods: POST

update_form:
    path: /user/update/{id}
    controller: App\Controller\UserController::updateForm
    methods: POST